entropy-code/entropay-employees

Dockerfile
docker-compose.yml
pom.xml
src/main/java/com/entropyteam/entropay/employees/EntropayEmployeesApplication.java
src/main/java/com/entropyteam/entropay/employees/ServletInitializer.java
src/main/resources/application.properties
src/test/java/com/entropyteam/entropay/employees/EntropayEmployeesApplicationTests.java

closes https://github.com/entropy-code/entropay-employees/issues/2

[#2] Add dockerfile

---

src/main/resources/db/migration/V5.0__DDL_add_company_and_tenant.sql

Fix migration script: remove gen_random_uuid() method

Fix migration script

---

.github/pull_request_template.md
.github/workflows/deploy-dev-aws.yml
.github/workflows/deploy-prod-aws.yml
src/test/java/com/entropyteam/entropay/employees/EntropayEmployeesApplicationTests.java

Add ci cd config to deploy into prod
https://entropyteam.atlassian.net/browse/EN-25

EN-25: add production deploy

---

src/main/java/com/entropyteam/entropay/employees/controllers/ContractController.java
src/main/java/com/entropyteam/entropay/employees/dtos/AssignmentDto.java
src/main/java/com/entropyteam/entropay/employees/dtos/ContractDto.java
src/main/java/com/entropyteam/entropay/employees/models/Assignment.java
src/main/java/com/entropyteam/entropay/employees/models/Contract.java
src/main/java/com/entropyteam/entropay/employees/models/Currency.java
src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
src/main/resources/db/migration/V13.0__DDL_add_fields_to_contract_and_assignment.sql
src/test/java/com/entropyteam/entropay/employees/controllers/ContractControllerTest.java
src/test/java/com/entropyteam/entropay/employees/services/ContractServiceTest.java
src/test/java/com/entropyteam/entropay/employees/testUtils/TestUtils.java

Added new fields to assignment and contract.

EN-4 & EN-6 Adding new values to assignment and contract

---

pom.xml
src/main/java/com/entropyteam/entropay/auth/AppRole.java
src/main/java/com/entropyteam/entropay/auth/AuthConstants.java
src/main/java/com/entropyteam/entropay/auth/SecureField.java
src/main/java/com/entropyteam/entropay/auth/SecureObjectService.java
src/main/java/com/entropyteam/entropay/common/BaseController.java
src/main/java/com/entropyteam/entropay/common/BaseService.java
src/main/java/com/entropyteam/entropay/common/exceptions/RestExceptionHandler.java
src/main/java/com/entropyteam/entropay/employees/controllers/CompanyController.java
src/main/java/com/entropyteam/entropay/employees/controllers/ConfigController.java
src/main/java/com/entropyteam/entropay/employees/controllers/ProjectController.java
src/main/java/com/entropyteam/entropay/employees/controllers/ProjectTypeController.java
src/main/java/com/entropyteam/entropay/employees/controllers/RoleController.java
src/main/java/com/entropyteam/entropay/employees/controllers/SeniorityController.java
src/main/java/com/entropyteam/entropay/employees/controllers/TenantController.java
src/main/java/com/entropyteam/entropay/employees/dtos/ConfigDto.java
src/main/java/com/entropyteam/entropay/employees/dtos/EmployeeDto.java
src/main/java/com/entropyteam/entropay/employees/dtos/MenuItemDto.java
src/main/java/com/entropyteam/entropay/employees/dtos/PermissionDto.java
src/main/java/com/entropyteam/entropay/employees/models/Assignment.java
src/main/java/com/entropyteam/entropay/employees/models/Config.java
src/main/java/com/entropyteam/entropay/employees/models/Contract.java
src/main/java/com/entropyteam/entropay/employees/repositories/ConfigRepository.java
src/main/java/com/entropyteam/entropay/employees/services/AssignmentService.java
src/main/java/com/entropyteam/entropay/employees/services/ConfigService.java
src/main/java/com/entropyteam/entropay/employees/services/ContractService.java
src/main/resources/db/migration/V14.0__DDL_fix_trigger_add config_entity.sql

- Adding permissions support
- Set permissions in model field level
- Retrieve menu from BE config 
- Configure exception handler
- Sql migration
https://entropyteam.atlassian.net/browse/EN-21
Tested manually

EN-21: set permisisons

---

src/main/resources/db/migration/V16.0__DDL_update_menu.sql

Add contracts and assignments to Menu
https://entropyteam.atlassian.net/browse/EN-43

EN-43: update menu with contracts and assignments

---

src/main/java/com/entropyteam/entropay/employees/dtos/AssignmentDto.java
src/main/java/com/entropyteam/entropay/employees/dtos/ContractDto.java
src/main/java/com/entropyteam/entropay/employees/models/Assignment.java
src/main/java/com/entropyteam/entropay/employees/models/Contract.java
src/main/resources/db/migration/V17.0__DDL_update_contract_and_assignment_table.sql
src/test/java/com/entropyteam/entropay/employees/testUtils/TestUtils.java

Field hours per week changes to hours per month in contract and assignment
https://entropyteam.atlassian.net/browse/EN-47

EN-47 Change hours per week to hours per month

---

src/main/java/com/entropyteam/entropay/employees/dtos/ClientDto.java
src/main/java/com/entropyteam/entropay/employees/models/Client.java
src/main/resources/db/migration/V18.0__DDL_update_client_table.sql

New fields add in client entity and db script
https://entropyteam.atlassian.net/browse/EN-37

EN-37: Contact field in Client

---

src/main/java/com/entropyteam/entropay/employees/controllers/TechnologyController.java
src/main/java/com/entropyteam/entropay/employees/dtos/EmployeeDto.java
src/main/java/com/entropyteam/entropay/employees/dtos/TechnologyDto.java
src/main/java/com/entropyteam/entropay/employees/models/Employee.java
src/main/java/com/entropyteam/entropay/employees/models/Technology.java
src/main/java/com/entropyteam/entropay/employees/repositories/TechnologyRepository.java
src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
src/main/java/com/entropyteam/entropay/employees/services/TechnologyService.java
src/main/resources/db/migration/V20.0__DDL_add_technology_table_update_menu.sql

New technology field in employee entity, db script with new tables and menu updated.
https://entropyteam.atlassian.net/browse/EN-55
New technology table
New employee technology table

EN-55: Add Technology field in profile

---

src/main/resources/db/migration/V20.1__DDL_update_menu.sql

Fix db script, menu option duplicated

EN-55: menu update, fix db script

---

.github/workflows/build.yml
.github/workflows/deploy-dev-aws.yml
Dockerfile
src/main/java/com/entropyteam/entropay/employees/services/ContractService.java
src/test/java/com/entropyteam/entropay/employees/services/ContractServiceTest.java
src/test/java/com/entropyteam/entropay/employees/testUtils/SecurityContextFactory.java

Fix test + run in pr
https://entropyteam.atlassian.net/browse/EN-64

EN-64: fix tests + run build on PR

---

src/main/resources/db/migration/V22.0__DML_update_permissions.sql

Sql script to set permissions on settings items
https://entropyteam.atlassian.net/browse/EN-66

EN-66: Add permissions to settings items

---

src/main/java/com/entropyteam/entropay/common/BaseService.java
src/main/java/com/entropyteam/entropay/employees/dtos/EmployeeDto.java
src/main/java/com/entropyteam/entropay/employees/models/Employee.java
src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
src/main/resources/db/migration/V24.0__DDL_update_employee.sql

Labour email add to employee entity
https://entropyteam.atlassian.net/browse/EN-67
New labour email column null

EN-67: New employee field

---

src/main/java/com/entropyteam/entropay/employees/dtos/EmployeeDto.java
src/main/java/com/entropyteam/entropay/employees/repositories/AssignmentRepository.java
src/main/java/com/entropyteam/entropay/employees/repositories/ContractRepository.java
src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java

- Enlarge employee dto response
https://entropyteam.atlassian.net/browse/EN-62
Manual testing

EN-62: Employee UI card

---

src/main/java/com/entropyteam/entropay/employees/controllers/LeaveTypeController.java
src/main/java/com/entropyteam/entropay/employees/dtos/LeaveTypeDto.java
src/main/java/com/entropyteam/entropay/employees/models/LeaveType.java
src/main/java/com/entropyteam/entropay/employees/repositories/LeaveTypeRepository.java
src/main/java/com/entropyteam/entropay/employees/services/LeaveTypeService.java
src/main/resources/db/migration/V26.0__DDL_create_leave_type_table_update_permissions.sql

New LeaveType entity added, its gonna be used when a time off is upload.
https://entropyteam.atlassian.net/browse/EN-77
Manual testing:
Get leave types
Post leave type
Edit leave type
Delete leave type

EN-77: add leave type entity

---

src/main/java/com/entropyteam/entropay/common/BaseService.java
src/main/java/com/entropyteam/entropay/common/Filter.java
src/main/java/com/entropyteam/entropay/common/ReactAdminMapper.java
src/main/java/com/entropyteam/entropay/employees/controllers/CountryController.java
src/main/java/com/entropyteam/entropay/employees/controllers/HolidayController.java
src/main/java/com/entropyteam/entropay/employees/dtos/CountryDto.java
src/main/java/com/entropyteam/entropay/employees/dtos/HolidayDto.java
src/main/java/com/entropyteam/entropay/employees/models/Country.java
src/main/java/com/entropyteam/entropay/employees/models/Holiday.java
src/main/java/com/entropyteam/entropay/employees/repositories/CountryRepository.java
src/main/java/com/entropyteam/entropay/employees/repositories/HolidayRepository.java
src/main/java/com/entropyteam/entropay/employees/services/CountryService.java
src/main/java/com/entropyteam/entropay/employees/services/HolidayService.java
src/main/java/com/entropyteam/entropay/employees/services/ProjectTypeService.java
src/main/resources/db/migration/V27.0__DDL_create_holiday_table_update_permissions.sql

New holiday and country entity.
https://entropyteam.atlassian.net/browse/EN-78
migrations succesfull 
country table
holiday_caldendar table

EN-78: Add holidays per location

---

src/main/java/com/entropyteam/entropay/employees/dtos/EmployeeDto.java
src/main/java/com/entropyteam/entropay/employees/repositories/PtoRepository.java
src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java

Nearest time off date is added to employeeDto 
https://entropyteam.atlassian.net/browse/EN-81
Manual testing

EN-81: See next time off of my employees

---

src/main/java/com/entropyteam/entropay/employees/dtos/ContractDto.java
src/main/java/com/entropyteam/entropay/employees/models/Contract.java
src/main/resources/db/migration/V33.0__DDL_remove_vacations_from_contract.sql
src/test/java/com/entropyteam/entropay/employees/common/ReactAdminMapperTest.java
src/test/java/com/entropyteam/entropay/employees/testUtils/TestUtils.java

The 'contract vacation' property was deleted from the model, as well as from the discount and the database.
https://entropyteam.atlassian.net/browse/EN-103

EN-103: Remove vacations from Contract

---

src/test/java/com/entropyteam/entropay/employees/services/EmployeeServiceTest.java

Hot fix in employee service test

Hot fix in employee service test

---

src/main/java/com/entropyteam/entropay/employees/controllers/VacationController.java

New endpoint add in order to test vacation job in dev enviroment. Only for Admin role
https://entropyteam.atlassian.net/browse/EN-107
Postman
S3 bucket files

EN-107: Vacation Job test

---

src/main/java/com/entropyteam/entropay/employees/dtos/PaymentInformationDto.java
src/main/java/com/entropyteam/entropay/employees/models/PaymentInformation.java
src/main/resources/db/migration/V37.0__DDL_update_payment_information_table.sql

routing number added to payment information
https://entropyteam.atlassian.net/browse/EN-54
A new employee with a routing number was created. then checked that the routing number was shown correctly.

EN-54 Add routing number to payment information

---

src/main/java/com/entropyteam/entropay/employees/services/AwsService.java

Fix to avoid errors on vacation job

Fix to avoid errors on vacation job

---

src/main/java/com/entropyteam/entropay/common/BaseService.java
src/main/java/com/entropyteam/entropay/employees/repositories/RoleRepository.java
src/main/java/com/entropyteam/entropay/employees/services/ContractService.java

Bug fix for hr filter in contracts
Manual testing

Fix for HR filter

---

src/main/java/com/entropyteam/entropay/common/exceptions/RestExceptionHandler.java
src/main/java/com/entropyteam/entropay/common/exceptions/dtos/ErrorResponseDto.java

Fixed "Server communication error" appearing whatever the error was, now all the error messages are more descriptive.
https://entropyteam.atlassian.net/browse/EN-116

EN-116: improved all error messages

---

src/main/java/com/entropyteam/entropay/employees/jobs/VacationJob.java
src/main/java/com/entropyteam/entropay/employees/models/Vacation.java
src/main/java/com/entropyteam/entropay/employees/services/VacationService.java

There was and error during pto deletion caused by a null value in the debit field of the vacations

HOTFIX: Error deleting ptos

---

src/main/java/com/entropyteam/entropay/employees/dtos/EmployeeReportDto.java

Fixed the date format on employees report
https://entropyteam.atlassian.net/browse/EN-120

EN-120: Fixed the date on employee reporting

---

src/main/java/com/entropyteam/entropay/employees/dtos/EmployeeReportDto.java
src/main/java/com/entropyteam/entropay/employees/models/Contract.java
src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
src/main/java/com/entropyteam/entropay/employees/services/ReportService.java

Fixed enddate not beint displayed in reports when theres no active contract for the employee
https://entropyteam.atlassian.net/browse/EN-122

EN-122: End date not displayed in reports.

---

src/main/java/com/entropyteam/entropay/employees/dtos/EmployeeDto.java
src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java

Added method for getting the time an employee has been working on the company
Added timeSinceStart attribute to EmployeeDto
https://entropyteam.atlassian.net/browse/EN-119

EN-119: Displaying an employees tenure on the company

---

src/main/java/com/entropyteam/entropay/common/BaseController.java
src/main/java/com/entropyteam/entropay/employees/services/GoogleService.java
src/main/java/com/entropyteam/entropay/employees/services/PtoService.java

Fix for event name and when we try to update or delete an event that is not in the calendar
https://entropyteam.atlassian.net/browse/EN-124

EN-124: fix for not found events

---

src/main/java/com/entropyteam/entropay/employees/repositories/AssignmentRepository.java
src/main/java/com/entropyteam/entropay/employees/repositories/ContractRepository.java

Fix for repository
https://entropyteam.atlassian.net/browse/EN-135

EN-135: fix repository

---

src/main/java/com/entropyteam/entropay/employees/controllers/HolidayController.java
src/main/java/com/entropyteam/entropay/employees/jobs/HolidayJob.java
src/main/java/com/entropyteam/entropay/employees/repositories/HolidayRepository.java
src/main/java/com/entropyteam/entropay/employees/services/HolidayService.java
src/main/resources/db/migration/V41.0__DDL_add_country_table.sql

It is added that the holidays are uploaded to the calendar, edited, and deleted, also the country ALL for the holidays for all countries and a job that runs at the beginning of the year to upload the holidays from the previous year
https://entropyteam.atlassian.net/browse/EN-138

EN-138: Add Holidays per country in shared google calendar

---

src/test/java/com/entropyteam/entropay/employees/services/EmployeeServiceTest.java

Fix vacation tests

---

src/main/resources/db/migration/V42.0__DDL_update_employee_table.sql

Fixed migrations
https://entropyteam.atlassian.net/browse/EN-136

EN-136Fix: Fix migrations

---

src/main/resources/db/migration/V42.0__DDL_update_employee_table.sql

https://entropyteam.atlassian.net/browse/EN-136

EN-136: Sql script fix

---

src/main/java/com/entropyteam/entropay/employees/controllers/ReportController.java
src/main/java/com/entropyteam/entropay/employees/dtos/PtoReportDetailDto.java
src/main/java/com/entropyteam/entropay/employees/repositories/AssignmentRepository.java
src/main/java/com/entropyteam/entropay/employees/repositories/PtoRepository.java
src/main/java/com/entropyteam/entropay/employees/services/ReportService.java

End point for getting details for pto reports by employee and by client
https://entropyteam.atlassian.net/browse/EN-146
https://entropyteam.atlassian.net/browse/EN-147
detail by client:
detail by employee:

EN-147/EN-146: Pto report detail by employee and client

---

src/main/java/com/entropyteam/entropay/employees/controllers/ReportController.java
src/main/java/com/entropyteam/entropay/employees/dtos/PtoReportClientDto.java
src/main/java/com/entropyteam/entropay/employees/dtos/PtoReportDetailDto.java
src/main/java/com/entropyteam/entropay/employees/dtos/PtoReportEmployeeDto.java
src/main/java/com/entropyteam/entropay/employees/repositories/AssignmentRepository.java
src/main/java/com/entropyteam/entropay/employees/repositories/ClientRepository.java
src/main/java/com/entropyteam/entropay/employees/repositories/PtoRepository.java
src/main/java/com/entropyteam/entropay/employees/services/ReportService.java
src/main/resources/db/migration/V46.0__DML_update_config_table.sql

Time off reporting total by client
Fixed bug on details by client and employee not filtering by year
https://entropyteam.atlassian.net/browse/EN-126

EN-126: Time off reporting total by client

---

src/main/java/com/entropyteam/entropay/employees/dtos/ClientDto.java
src/main/java/com/entropyteam/entropay/employees/models/Client.java
src/main/resources/db/migration/V48.0__DDL_update_client_table.sql

Created new field for client, called "internalId" and also created script to update already existing clients with their respective internal id
https://entropyteam.atlassian.net/browse/EN-158

EN-158: Added new field to client and created script to update it

---

src/main/java/com/entropyteam/entropay/employees/dtos/ClientDto.java
src/main/java/com/entropyteam/entropay/employees/models/Client.java
src/main/java/com/entropyteam/entropay/employees/services/ClientService.java
src/main/resources/db/migration/V51.0__DDL_update_client_table.sql

Added new field to client
Added check before deactivating a client
https://entropyteam.atlassian.net/browse/EN-154

EN-154: Added new field to client and check to see if its deactivable

---

src/main/java/com/entropyteam/entropay/common/BuilderUtils.java
src/main/java/com/entropyteam/entropay/employees/controllers/VacationController.java
src/main/java/com/entropyteam/entropay/employees/dtos/VacationDto.java
src/main/java/com/entropyteam/entropay/employees/jobs/VacationJob.java
src/main/java/com/entropyteam/entropay/employees/models/Vacation.java
src/main/java/com/entropyteam/entropay/employees/repositories/VacationRepository.java
src/main/java/com/entropyteam/entropay/employees/services/VacationService.java
src/main/resources/db/migration/V52.0__DDL_update_vacation_table.sql
src/test/java/com/entropyteam/entropay/employees/services/VacationServiceTest.java

Job to expire vacations policy
https://entropyteam.atlassian.net/browse/EN-151

EN-151: Expired vacations policy

---

src/main/java/com/entropyteam/entropay/employees/controllers/ReportController.java
src/main/java/com/entropyteam/entropay/employees/services/ReportService.java

Added an endpoint to get all details from ptos reports
https://entropyteam.atlassian.net/browse/EN-161

EN-161: End point for all pto report detaills

---

src/main/resources/db/migration/V53.0__DML_update_config_table.sql

Removed delete privileges for "clients", "projects" and "projects" for all roles except admin role.
https://entropyteam.atlassian.net/browse/EN-153

EN-153: Updated permissions for some entities

---

src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
src/test/java/com/entropyteam/entropay/employees/services/EmployeeServiceTest.java

Tech debt in vacation job
https://entropyteam.atlassian.net/browse/EN-137
Uni tests

EN-157: fix vacation job

---

pom.xml
src/main/java/com/entropyteam/entropay/employees/services/AwsCredentialsProperties.java
src/main/java/com/entropyteam/entropay/employees/services/GoogleCredentialsProperties.java

A long time ago we decided to not use lombok and mapstruct. Removing those dependencies
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/7392103586
`mvn clean package` and started the application locally. Will test more in dev

Removing lombok and mapstruct dependencies

---

pom.xml

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Executed locally:
```
C:\Users\eazar\entropay\entropay-employees [eazaretzky/flyway-upgrade +1 ~0 -0 | +0 ~2 -0 !]> mvn flyway:migrate
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------< com.entropyteam.entropay:entropay-employees >-------------
[INFO] Building entropay-employees 1.1.26-SNAPSHOT
[INFO] --------------------------------[ jar …
```

use flyway version managed by spring boot parent pom

---

docker-compose.yml
pom.xml
src/main/java/com/entropyteam/entropay/common/ReactAdminParams.java
src/main/java/com/entropyteam/entropay/common/ReactAdminSqlMapper.java
src/main/java/com/entropyteam/entropay/common/ReactAdminSqlParams.java
src/main/java/com/entropyteam/entropay/employees/controllers/ReportController.java
src/main/java/com/entropyteam/entropay/employees/dtos/SalariesReportDto.java
src/main/java/com/entropyteam/entropay/employees/repositories/EmployeeRepository.java
src/main/java/com/entropyteam/entropay/employees/repositories/ReportRepository.java
src/main/java/com/entropyteam/entropay/employees/repositories/ReportRepositoryImpl.java
src/main/java/com/entropyteam/entropay/employees/services/ReportService.java
src/main/resources/db/migration/V55.0__DML_update_config_table.sql
src/test/java/com/entropyteam/entropay/common/ReactAdminSqlMapperTest.java

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/7575301701

creation of a report that is used to pay the salaries

---

src/main/resources/application.properties

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

enable virtual threads

---

src/main/java/com/entropyteam/entropay/employees/controllers/EndReasonController.java
src/main/java/com/entropyteam/entropay/employees/dtos/ContractDto.java
src/main/java/com/entropyteam/entropay/employees/dtos/EndReasonDto.java
src/main/java/com/entropyteam/entropay/employees/models/Contract.java
src/main/java/com/entropyteam/entropay/employees/models/EndReason.java
src/main/java/com/entropyteam/entropay/employees/repositories/EndReasonRepository.java
src/main/java/com/entropyteam/entropay/employees/services/ContractService.java
src/main/java/com/entropyteam/entropay/employees/services/EndReasonService.java
src/main/resources/db/migration/V57.0__DDL_create_end_reason_table_update_contract_table.sql
src/main/resources/db/migration/V58.0__DML_update_config_table.sql
src/test/java/com/entropyteam/entropay/employees/services/ContractServiceTest.java
src/test/java/com/entropyteam/entropay/employees/testUtils/TestUtils.java

This pull request have the implementation of the end reasons of contracts.
I took the existing "Role" implementation as a reference to implement this new function.

End reason implementation for Contracts

---

src/main/java/com/entropyteam/entropay/employees/controllers/OvertimeController.java
src/main/java/com/entropyteam/entropay/employees/dtos/OvertimeDto.java
src/main/java/com/entropyteam/entropay/employees/models/Overtime.java
src/main/java/com/entropyteam/entropay/employees/repositories/OvertimeRepository.java
src/main/java/com/entropyteam/entropay/employees/services/OvertimeService.java
src/main/resources/db/migration/V61.0__DDL_create_overtime_table.sql

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

overtime logic

---

src/main/resources/db/migration/V62.0__DML_update_config_table.sql

Update config for overtimes.
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/7313297206
Tested locally.

Update config to add overtimes to menu and roles

---

src/main/java/com/entropyteam/entropay/employees/services/OvertimeService.java

[Add search feature for overtime](https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/7313297206)
Tested locally

Add search feature for overtime

---

src/main/resources/db/migration/V63.0__DML_update_config_table.sql

Restore salaries report.
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/8064892861
Locally.

Restore salaries report

---

src/main/java/com/entropyteam/entropay/common/DateRangeDto.java
src/main/java/com/entropyteam/entropay/employees/controllers/ReportController.java
src/main/java/com/entropyteam/entropay/employees/models/Assignment.java
src/main/java/com/entropyteam/entropay/employees/repositories/AssignmentRepository.java
src/main/java/com/entropyteam/entropay/employees/repositories/HolidayRepository.java
src/main/java/com/entropyteam/entropay/employees/repositories/PtoRepository.java
src/main/java/com/entropyteam/entropay/employees/services/BillingService.java

Introduced a new billing report feature in ReportController leveraging the newly added BillingService.

Add billing report generation and related enhancements

---

src/main/java/com/entropyteam/entropay/common/ReactAdminMapper.java
src/main/java/com/entropyteam/entropay/common/ReactAdminParams.java
src/main/java/com/entropyteam/entropay/employees/controllers/ReportController.java
src/main/java/com/entropyteam/entropay/employees/dtos/EmployeeReportDto.java
src/main/java/com/entropyteam/entropay/employees/dtos/PtoReportClientDto.java
src/main/java/com/entropyteam/entropay/employees/dtos/PtoReportDetailDto.java
src/main/java/com/entropyteam/entropay/employees/dtos/PtoReportEmployeeDto.java
src/main/java/com/entropyteam/entropay/employees/dtos/ReportDto.java
src/main/java/com/entropyteam/entropay/employees/services/BillingService.java

Updated the reporting structure by introducing a generic `ReportDto` to encapsulate data and size, replacing specific extensions in report DTOs. Refactored `generateBilling` to `generateBillingReport` for improved sorting, pagination, and clarity in the billing service. Added utility methods in `ReactAdminParams` for enhanced functionality.

Refactor reporting and billing services to use ReportDto.

---

src/main/java/com/entropyteam/entropay/employees/services/BillingService.java

Updated BillingService to include PTO hours in billing calculations. Modified BillingDto and BillingEntry to support PTO data and integrated it into report generation logic. Adjusted sublist handling to prevent out-of-bounds errors.

Add PTO hours tracking to BillingService

---

src/main/java/com/entropyteam/entropay/employees/models/Pto.java
src/main/java/com/entropyteam/entropay/employees/services/BillingService.java

Replaced PTO day calculations with PTO hour aggregation for better precision in billing reports. Introduced a new `getPtoDays` method in the `Pto` class and adjusted logic in `BillingService` to account for this change. Added transactional annotation and extracted pagination logic for cleaner code structure.

Refactor PTO handling and optimize billing report generation.

---

src/main/java/com/entropyteam/entropay/employees/controllers/ReportController.java
src/main/java/com/entropyteam/entropay/employees/models/Contract.java
src/main/java/com/entropyteam/entropay/employees/models/Employee.java
src/main/java/com/entropyteam/entropay/employees/models/Pto.java
src/main/java/com/entropyteam/entropay/employees/repositories/ContractRepository.java
src/main/java/com/entropyteam/entropay/employees/services/AssignmentService.java
src/main/java/com/entropyteam/entropay/employees/services/BillingService.java
src/main/java/com/entropyteam/entropay/employees/services/ContractService.java
src/main/java/com/entropyteam/entropay/employees/services/MarginService.java
src/main/java/com/entropyteam/entropay/employees/services/OvertimeService.java
src/main/java/com/entropyteam/entropay/employees/services/PtoService.java
src/main/java/com/entropyteam/entropay/employees/timetracking/ActivityType.java
src/main/java/com/entropyteam/entropay/employees/timetracking/AssignmentTimeEntry.java
src/main/java/com/entropyteam/entropay/employees/timetracking/OvertimeTimeEntry.java
src/main/java/com/entropyteam/entropay/employees/timetracking/PtoTimeEntry.java
src/main/java/com/entropyteam/entropay/employees/timetracking/TimeTrackingEntry.java
src/main/resources/db/migration/V67.0__DDL_update_menu_billing_report.sql
src/test/java/com/entropyteam/entropay/employees/services/BillingServiceTest.java

Implemented a new `MarginService` to generate margin reports for employees and assignments. Introduced new time tracking entities (`AssignmentTimeEntry`, `PtoTimeEntry`, etc.) to streamline activity management. Updated related services and repositories, along with corresponding API changes, permission updates, and database migration.
---
This pull request includes several changes to the `ReportController`, `Contract`, `Employee`, `Pto`, and various service classes to add new features and improve functionality. The most important changes include adding a new endpoint for margin reports, enhancing the `Contract` model to calculate payment settlements, and updating the `AssignmentService` and `BillingService` to handle assignment activities more effectively.
* Added a new `MarginService` …

Add margin report functionality and optimize time tracking

---

src/main/java/com/entropyteam/entropay/employees/controllers/EmployeeFeedbackController.java
src/main/java/com/entropyteam/entropay/employees/dtos/FeedbackDto.java
src/main/java/com/entropyteam/entropay/employees/models/EmployeeFeedback.java
src/main/java/com/entropyteam/entropay/employees/models/FeedbackSource.java
src/main/java/com/entropyteam/entropay/employees/repositories/EmployeeFeedbackRepository.java
src/main/java/com/entropyteam/entropay/employees/services/EmployeeFeedbackService.java
src/main/resources/db/migration/V68.0__DDL_create_feedback_table.sql

This pull request introduces a new feature for managing employee feedback in the system. It includes the creation of a new feedback module, consisting of a controller, DTO, service, repository, and database table, as well as updates to permissions and the UI menu to support the new functionality.
* **Controller and Service Layer:**
- Added `EmployeeFeedbackController` to handle API requests for employee feedback, extending the `BaseController` for CRUD operations. (`EmployeeFeedbackController.java`)
- Created `EmployeeFeedbackService` to manage business logic, including setting the `createdBy` field based on the current authenticated user. (`EmployeeFeedbackService.java`)
* **Data Models and Repository:**
- Introduced `EmployeeFeedback` entity to represent feedback data, including fields …

Add employee feedback management functionality

---

src/main/java/com/entropyteam/entropay/common/ReactAdminMapper.java
src/main/java/com/entropyteam/entropay/common/ReactAdminParams.java
src/main/java/com/entropyteam/entropay/employees/services/BillingService.java
src/main/java/com/entropyteam/entropay/employees/services/MarginService.java
src/test/java/com/entropyteam/entropay/common/ReactAdminParamsTest.java

This pull request introduces a new filtering mechanism to the `ReactAdminMapper` and integrates it into the `ReactAdminParams` class, enabling dynamic filtering of data based on attributes. It also updates the services to use this filtering mechanism and adds comprehensive unit tests to validate the functionality.
* **Added `getFilter` Method in `ReactAdminMapper`:** Introduced a static method that generates a `Predicate` for filtering objects based on specified attributes. Special handling is included for date range fields (`startDate`, `endDate`) and search terms (`q`) across `firstName` and `lastName`.
* **Integrated `getFilter` in `ReactAdminParams`:** Added a `getFilter` method in `ReactAdminParams` that delegates to `ReactAdminMapper.getFilter`, allowing its use directly from …

Add filtering support to ReactAdminParams and related services

---

src/main/java/com/entropyteam/entropay/employees/models/Contract.java
src/main/java/com/entropyteam/entropay/employees/services/AssignmentService.java
src/test/java/com/entropyteam/entropay/employees/services/MarginServiceTest.java

Added a comprehensive test suite for MarginService to validate margin report generation. Enhanced Contract and AssignmentService logic to ensure accurate handling of payment settlements and working days, respectively.

Add unit tests for MarginService and improve related logic

---

src/main/java/com/entropyteam/entropay/common/ReactAdminMapper.java
src/main/java/com/entropyteam/entropay/employees/controllers/ReportController.java
src/main/java/com/entropyteam/entropay/employees/services/AssignmentService.java
src/main/java/com/entropyteam/entropay/employees/services/BillingService.java
src/main/java/com/entropyteam/entropay/employees/services/MarginService.java
src/main/java/com/entropyteam/entropay/employees/services/ReportService.java
src/main/java/com/entropyteam/entropay/employees/services/TurnoverService.java
src/test/java/com/entropyteam/entropay/employees/services/AssignmentServiceTest.java

This pull request refactors the report generation and pagination logic across multiple services to centralize and streamline the implementation. The key change is the introduction of a generic `paginate` method in `ReactAdminMapper`, which replaces custom pagination logic in several services. This improves code reuse, maintainability, and consistency for paginated report responses.
**Pagination Refactoring**
* Added a generic `paginate` method to `ReactAdminMapper` for filtering, sorting, and paginating lists, returning a standardized `ReportDto<T>` result. This method is now used for all report pagination.
* Removed custom pagination methods from `BillingService`, `MarginService`, and `TurnoverService`, replacing their usages with the new centralized `paginate` method. …

Refactor billing and margin services to improve pagination logic
