entropy-code/entropay-employees

- src/main/java/com/entropyteam/entropay/config/WebSecurityConfig.java
- src/main/java/com/entropyteam/entropay/employees/controllers/ContractController.java
- src/main/java/com/entropyteam/entropay/employees/controllers/EmployeeController.java
- src/main/java/com/entropyteam/entropay/employees/dtos/ContractDto.java
- src/main/java/com/entropyteam/entropay/employees/models/Address.java
- src/main/java/com/entropyteam/entropay/employees/models/Contract.java
- src/main/java/com/entropyteam/entropay/employees/models/Employee.java
- src/main/java/com/entropyteam/entropay/employees/models/Role.java
- src/main/java/com/entropyteam/entropay/employees/repositories/ContractRepository.java
- src/main/java/com/entropyteam/entropay/employees/services/ContractService.java
- src/main/resources/db/migration/V8.0__DDL_modify_contract_table.sql
- src/test/java/com/entropyteam/entropay/employees/controllers/ContractControllerTest.java
- src/test/java/com/entropyteam/entropay/employees/services/ContractServiceTest.java
- src/test/java/com/entropyteam/entropay/employees/testUtils/testUtils.java
New features:
1. Create a new contract.
a. ContractService verifies if an employee has an existing active contract, and deactivates it before creating the new one.
b. A new flyway migration script has been added with a boolean attribute _active_ for contracts. The default value is intentionally set to false to avoid unintended active contracts on the DB.
c. A trigger on the DB has been created to ensure every INSERT or UPDATE validates that there is only one active contract per employee.
d. **PLUS**: A trigger on the DB has been created to update _modified_at_ attribute when any change is performed.
2. Modify an existing contract status.
a. Created new endpoint `/contracts/{id}` for PATCH requests.
b. ContractService will validate data consistency and also deactivate any previous active …
> EN-22 Modify employee contracts status

- src/main/resources/db/migration/V9.0_modify_contract_validation_trigger.sql
Detected errors while creating new contracts. SQL Function on_active_status_validate_unique() was comparing an integer with a boolean throwing an error.
https://entropyteam.atlassian.net/browse/EN-22
Live tests on local environment sending POST requests to create a new contract with different "active" values. All end up creating a new contract.
When trying to activate a second contract for the same employee, the trigger does return an error. This error can only be triggered while modifying manually the DB.
> EN-22 Modify contract validation trigger

- src/main/java/com/entropyteam/entropay/employees/repositories/ContractRepository.java
- src/main/java/com/entropyteam/entropay/employees/services/ContractService.java
- src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
- src/main/java/com/entropyteam/entropay/employees/services/PaymentInformationService.java
- src/main/java/com/entropyteam/entropay/employees/services/PaymentSettlementService.java
- src/main/resources/db/migration/V25.0__DDL_remove_trigger_from_contract.sql
- src/test/java/com/entropyteam/entropay/employees/services/ContractServiceTest.java
The contract status now is based on due date
https://entropyteam.atlassian.net/browse/EN-72
Manual testing.
the following cases were tested:
the following cases were tested:
1. New active contract: when a new valid contract is created it is active
2. New inactive contract: when a new contract has end date before now it is inactive
3. New contract with end date null is active: when a new contract has null end date it is active
4. New contract with start date after now and end date after start date is inactive
5. Inactive last active contract when a new active contract is created: when a new active contract is created the last active contract is set inactive
6. Last active contract stays active when inactive contract is created
7. Last active …
> EN-72: Contract status based on Due date

- src/main/java/com/entropyteam/entropay/common/BaseService.java
- src/main/java/com/entropyteam/entropay/common/Filter.java
- src/main/java/com/entropyteam/entropay/common/ReactAdminMapper.java
- src/main/java/com/entropyteam/entropay/employees/controllers/ContractController.java
- src/main/java/com/entropyteam/entropay/employees/dtos/EmployeeDto.java
- src/main/java/com/entropyteam/entropay/employees/services/ContractService.java
When a new contract/employee is created from employees profile, the latest active information is prefill in the form.
https://entropyteam.atlassian.net/browse/EN-76
Manual testing:
-New assignment from employees prefill the assignment with null end date.
-New assignment from an employee without assignment only prefill the employee's name
-New contract from employees prefill the contract with active status.
-New contract from an employee without contracts only prefill the employee's name
> EN-76: Prefill new contract/assignment with active information

- src/main/java/com/entropyteam/entropay/employees/dtos/AssignmentDto.java
- src/main/java/com/entropyteam/entropay/employees/models/Assignment.java
- src/main/java/com/entropyteam/entropay/employees/services/AssignmentService.java
- src/main/resources/db/migration/V28.0__DDL_update_assignment_table_update_active.sql
Added the active value to the Assignment entity, currently by default, all assignments are set to the 'active' value as true.
https://entropyteam.atlassian.net/browse/EN-93
Successfully ran the command mvn flyway:migrate
This is how the Assignment entity looks with its active value set to true
> EN-93: Add active field to Assignment entity

- src/main/java/com/entropyteam/entropay/employees/dtos/AssignmentDto.java
- src/main/java/com/entropyteam/entropay/employees/repositories/AssignmentRepository.java
- src/main/java/com/entropyteam/entropay/employees/services/AssignmentService.java
The ability has been added for Assignments, when created, to set "active" to true based on the entered date. If there was a previous Assignment, it will automatically set it to "active" false. This logic also applies to the update.
https://entropyteam.atlassian.net/browse/EN-95
Here is the incorporated logic for dates, where the most important conditions are:
The end date is null (ongoing contract).
The end date is after the current date (ongoing contract).
The start date is before the current date (active contract).
The start date is equal to the current date (contract starting today).
Here I show how it was tested by creating an Assignment, the first one was set to true, and upon creating the newest one, it was also set to true.
> EN-95:  Set active field to Assignment entity

- src/main/java/com/entropyteam/entropay/employees/controllers/HolidayController.java
- src/main/java/com/entropyteam/entropay/employees/repositories/HolidayRepository.java
- src/main/java/com/entropyteam/entropay/employees/services/HolidayService.java
Added endpoint was created to bring the years of all the holidays already ordered and without repeating
https://entropyteam.atlassian.net/browse/EN-102
The query used to fetch the years
Format of the data that it returns so as not to have problems in react admin
> EN-102: Tech debt on holidays component

- src/main/java/com/entropyteam/entropay/employees/dtos/SeniorityDto.java
- src/main/java/com/entropyteam/entropay/employees/models/Seniority.java
- src/main/java/com/entropyteam/entropay/employees/repositories/EmployeeRepository.java
- src/main/java/com/entropyteam/entropay/employees/repositories/VacationRepository.java
- src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
- src/main/resources/db/migration/V34.0__DDL_update_seniority_table.sql
- src/test/java/com/entropyteam/entropay/employees/services/EmployeeServiceTest.java
New method to get vacations for employee based on seniority
https://entropyteam.atlassian.net/browse/EN-105
Migration success
Unit tests
Cases tested:
1. Apply vacations rule to a old Tr/Jr/Ssr employee
2. Apply vacations rule to a old Sr/Architec employee
3. Apply vacations rule to a new Tr/Jr/Ssr employee
4. Apply vacations rule to a new Sr/Architec employee
5. Apply vacations rule to a employee with 2 years in entropy
6. Apply vacations to a employee with vacations
> EN-105: Vacation creation job

- src/main/java/com/entropyteam/entropay/employees/dtos/PtoDto.java
- src/main/java/com/entropyteam/entropay/employees/models/Pto.java
- src/main/java/com/entropyteam/entropay/employees/services/PtoService.java
- src/main/resources/db/migration/V40.0__DDL_update_pto_table.sql
- src/test/java/com/entropyteam/entropay/employees/services/PtoServiceTest.java
Added the ability to take half a day off when creating a PTO.
Added unit tests related to this feature.
https://entropyteam.atlassian.net/browse/EN-118
> Added the ability to take half a day off when requesting a PTO

- src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
Fixed end date not being displayed in profile when there's no active contract, now shows the end date of the latest contract
https://entropyteam.atlassian.net/browse/EN-122
> EN-122: End date not being displayed in profile

- src/main/java/com/entropyteam/entropay/employees/services/PtoService.java
This PR adds the Pto's  event creation on Google Calendar
https://entropyteam.atlassian.net/browse/EN-114
Tested on local environment with a personal google calendar account.
> EN-114 Pto calendar event creation

- src/main/java/com/entropyteam/entropay/employees/jobs/VacationJob.java
Fixed vacations credit not being added to the correct year
> EN-132: Fixed vacation credit set to right year

- src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
Fixed bug that does not allow the employee to be edited if it does not have a birthDate
https://entropyteam.atlassian.net/browse/EN-152
> EN-152: Error editing employee without birthdate

- src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
- src/test/java/com/entropyteam/entropay/employees/services/EmployeeServiceTest.java
This change adds new vacation rule for 5 years old Employees
https://entropyteam.atlassian.net/browse/EN-150
Tested through UI with "vacations/set-vacations" endpoint with three employees with different ages, simulating both October 1st and current date execution.
> EN-150 20 days vacation credit for 5 years old employees

- src/main/java/com/entropyteam/entropay/employees/models/Client.java
- src/main/resources/db/migration/V44.0__DDL_update_client_table.sql
Deleted a constraint enabling clients to be created once they have been deleted
https://entropyteam.atlassian.net/browse/EN-155
> EN-155: Cannot create a client once it was Deleted

- src/main/java/com/entropyteam/entropay/employees/dtos/PtoReportClientDto.java
- src/main/java/com/entropyteam/entropay/employees/repositories/AssignmentRepository.java
- src/main/java/com/entropyteam/entropay/employees/repositories/EmployeeRepository.java
- src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
- src/main/java/com/entropyteam/entropay/employees/services/ReportService.java
In time off reporting those employees that do not have an assigned client now appear on the Gropy by Client under "No client" name.
Group by client detail is also working and shows the details of those ptos taken by employees without an assigned client
https://entropyteam.atlassian.net/browse/EN-162
> EN-162: Displayed unassigned Client when group by Client

- src/main/resources/db/migration/V54.0__DML_update_config_table.sql
Removed menu option for ptos report by client now that theres a selector for the group by used in the report
Renamed the menu option for Ptos report by employee to simply "PTOs"
https://entropyteam.atlassian.net/browse/EN-163
> EN-163: Removed menu option: ptos report by client

- src/main/java/com/entropyteam/entropay/employees/calendar/GoogleCalendarService.java
We were using the ID of the leave event in DB format instead of the custom format for leave events.
https://3.basecamp.com/5776473/buckets/37034902/todos/7928527109
Tested locally.
> Fix issue with leave events not being deleted from calendar

- src/main/java/com/entropyteam/entropay/employees/jobs/BirthdayJob.java
- src/test/java/com/entropyteam/entropay/employees/jobs/BirthdayJobTest.java
This pull request introduces a new scheduled job, `BirthdayJob`, to notify about employee birthdays and includes comprehensive unit tests to validate its functionality. The key changes are as follows:
* Added the `BirthdayJob` class in `src/main/java/com/entropyteam/entropay/employees/jobs/BirthdayJob.java`. This job:
- Runs Monday-Friday at 9:00 AM GMT-3.
- Notifies about employee birthdays, including weekend birthdays on Mondays.
- Filters active and non-deleted employees and checks their birth dates against the current date or weekend dates.
* Added the `BirthdayJobTest` class in `src/test/java/com/entropyteam/entropay/employees/jobs/BirthdayJobTest.java` to test the functionality of `BirthdayJob`. Key tests include:
- Verifying notifications are sent for employees with birthdays on …
> Add BirthdayJob to notify employee birthdays

- src/main/resources/db/migration/V74.0__DML_remove_pto_categories_submenu.sql
Removes PTO report permissions and the PTO categories submenu from the Reports section for ROLE_HR_DIRECTOR, ROLE_ADMIN, ROLE_MANAGER_HR, and ROLE_DEVELOPMENT in the config table. Updates the menu and permissions to reflect these changes for each role.
> Remove PTO categories submenu and permissions
